"use client"

import { motion } from 'framer-motion'
import { useRouter } from 'next/navigation'
import { Timer, Zap, Trophy, Brain, Target, CalendarDays, Mic, CheckCircle2 } from 'lucide-react'
import { GradientButton } from '@/components/ui/GradientButton'
import { useEffect, useState } from 'react'

export default function ChallengesHubPage() {
    const router = useRouter()
    const [timeLeftDay, setTimeLeftDay] = useState("")

    useEffect(() => {
        const updateCountdown = () => {
            const now = new Date()
            const endOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59)
            const diff = endOfDay.getTime() - now.getTime()

            const h = Math.floor((diff / (1000 * 60 * 60)) % 24)
            const m = Math.floor((diff / 1000 / 60) % 60)
            const s = Math.floor((diff / 1000) % 60)

            setTimeLeftDay(`${h.toString().padStart(2, '0')}h ${m.toString().padStart(2, '0')}m ${s.toString().padStart(2, '0')}s`)
        }

        updateCountdown()
        const timer = setInterval(updateCountdown, 1000)
        return () => clearInterval(timer)
    }, [])

    return (
        <div className="min-h-screen bg-[#080810] text-white p-4 md:p-8 pb-24">
            <div className="max-w-6xl mx-auto space-y-8">

                {/* Header */}
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
                    <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}>
                        <h1 className="text-4xl md:text-5xl font-black font-heading tracking-tight mb-2">
                            Challenges <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-400 to-orange-500">Arena</span>
                        </h1>
                        <p className="text-zinc-400 text-lg">Push your limits with bite-sized daily exercises.</p>
                    </motion.div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

                    {/* Daily Challenge (Featured) */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="md:col-span-2 bg-gradient-to-br from-[#1a150f] to-[#0f0f1a] border border-amber-500/20 rounded-3xl p-6 md:p-8 relative overflow-hidden group flex flex-col justify-between"
                    >
                        <div className="absolute top-0 left-0 w-64 h-64 bg-amber-500/10 blur-[80px] pointer-events-none group-hover:bg-amber-500/20 transition-colors" />

                        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 z-10 mb-8">
                            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-400 text-xs font-bold uppercase tracking-wider">
                                <CalendarDays className="w-4 h-4" /> Daily AI Prompt
                            </div>
                            <div className="flex items-center gap-2 bg-black/40 border border-white/10 px-4 py-2 rounded-xl text-amber-300 font-mono text-sm shadow-inner">
                                <Timer className="w-4 h-4" /> {timeLeftDay}
                            </div>
                        </div>

                        <div className="z-10 mb-8">
                            <h2 className="text-3xl font-bold text-white mb-2">The Setup</h2>
                            <p className="text-zinc-400">Read today's fresh scenario generated by NOVA and record a 2-minute response. Graded globally.</p>
                        </div>

                        <div className="z-10 flex flex-col sm:flex-row gap-4 items-center justify-between border-t border-white/5 pt-6">
                            <div className="flex -space-x-2">
                                {[1, 2, 3, 4].map(i => (
                                    <div key={i} className="w-8 h-8 rounded-full border-2 border-[#1a150f] bg-zinc-800" />
                                ))}
                                <div className="w-8 h-8 rounded-full border-2 border-[#1a150f] bg-zinc-800 flex items-center justify-center text-[10px] text-zinc-400">+1k</div>
                                <span className="ml-4 text-xs text-zinc-500 font-bold">Have played today</span>
                            </div>
                            <GradientButton onClick={() => router.push('/challenges/daily')} className="w-full sm:w-auto px-8 py-3 from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400">
                                Start Daily Challenge <Mic className="w-4 h-4 ml-2" />
                            </GradientButton>
                        </div>
                    </motion.div>

                    {/* Grammar Blitz */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.1 }}
                        className="bg-gradient-to-br from-[#0f0a1a] to-[#0f0f1a] border border-fuchsia-500/20 rounded-3xl p-6 md:p-8 relative overflow-hidden group flex flex-col justify-between"
                    >
                        <div className="absolute top-0 right-0 w-32 h-32 bg-fuchsia-500/20 blur-[50px] pointer-events-none group-hover:bg-fuchsia-500/30 transition-colors" />

                        <div className="z-10 mb-6">
                            <div className="w-12 h-12 rounded-2xl bg-fuchsia-500/10 border border-fuchsia-500/20 flex items-center justify-center mb-6">
                                <Brain className="w-6 h-6 text-fuchsia-400" />
                            </div>
                            <h3 className="text-2xl font-bold mb-2">Grammar Blitz</h3>
                            <p className="text-zinc-400 text-sm">10 rapid-fire Multiple Choice Questions. 30 seconds each. Zero mistakes allowed.</p>
                        </div>

                        <button onClick={() => router.push('/challenges/blitz')} className="z-10 w-full py-4 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-white font-bold transition-all hover:border-fuchsia-500/50 flex flex-col items-center justify-center gap-1">
                            Enter Blitz <span className="text-xs font-normal text-zinc-500">+100 XP Mastery</span>
                        </button>
                    </motion.div>

                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    {/* Timed Modules */}
                    {[
                        { id: '30s', name: 'Quick Spark', dur: '30 sec', icon: Zap, color: 'text-yellow-400', border: 'border-yellow-500/20', bg: 'hover:bg-yellow-500/5' },
                        { id: '60s', name: 'Speed Talk', dur: '60 sec', icon: Target, color: 'text-emerald-400', border: 'border-emerald-500/20', bg: 'hover:bg-emerald-500/5' },
                        { id: '2m', name: 'Power Pitch', dur: '2 min', icon: Mic, color: 'text-blue-400', border: 'border-blue-500/20', bg: 'hover:bg-blue-500/5' },
                        { id: '5m', name: 'Deep Dive', dur: '5 min', icon: Brain, color: 'text-purple-400', border: 'border-purple-500/20', bg: 'hover:bg-purple-500/5' }
                    ].map((mode, i) => (
                        <motion.button
                            key={mode.id}
                            onClick={() => router.push(`/challenges/${mode.id}`)}
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.2 + (i * 0.1) }}
                            className={`p-6 rounded-3xl border ${mode.border} bg-white/[0.02] ${mode.bg} transition-all text-left flex flex-col gap-4 relative overflow-hidden group`}
                        >
                            <div className="flex items-start justify-between">
                                <div className={`w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center ${mode.color}`}>
                                    <mode.icon className="w-5 h-5" />
                                </div>
                                <span className="text-xs font-mono font-bold text-zinc-500 group-hover:text-white transition-colors">{mode.dur}</span>
                            </div>
                            <div>
                                <h4 className="text-lg font-bold text-white mb-1 group-hover:text-amber-300 transition-colors">{mode.name}</h4>
                                <p className="text-sm text-zinc-500">Timed fluency sprint</p>
                            </div>
                        </motion.button>
                    ))}
                </div>

                {/* Weekly Leaderboard Panel */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.6 }}
                    className="bg-white/5 border border-white/10 rounded-3xl p-6 md:p-8 flex flex-col items-center justify-center text-center mt-12"
                >
                    <Trophy className="w-12 h-12 text-zinc-600 mb-4" />
                    <h3 className="text-xl font-bold mb-2">Weekly Grandmaster Challenge</h3>
                    <p className="text-zinc-400 max-w-md mx-auto mb-6">Complete the most challenges this week to secure the exclusive Grandmaster Badge. Resets on Sunday midnight.</p>
                    <button onClick={() => router.push('/dashboard')} className="px-6 py-2 bg-white/10 hover:bg-white/20 rounded-full text-sm font-bold transition-colors">
                        View Leaderboard on Dashboard
                    </button>
                </motion.div>

            </div>
        </div>
    )
}
